export const REPOSITORY_SYMBOL = Symbol('REPOSITORY_SYMBOL')
export const ENTITY_SYMBOL = Symbol()
export const ONETOONE_SYMBOL = Symbol()
export const PRIMARY_COLUMN_SYMBOL = Symbol()
export const RELATION_SYMBOL = Symbol('RELATION_SYMBOL')
export const ENTITY_COLUMN_SYMBOL = Symbol('ENTITY_COLUMN_SYMBOL')
